<?php

use App\Models\BlockedDate;
use App\Models\Booking;
use App\Models\Destination;
use App\Models\Payment;
use App\Models\Review;
use App\Models\ReviewToken;
use App\Models\Villa;
use App\Models\VillaIcalLink;

// =====================================================
// Villa Model Tests
// =====================================================

it('can create a villa', function () {
    $villa = Villa::factory()->create([
        'name' => 'Villa Test',
        'slug' => 'villa-test',
        'location' => 'Yogyakarta, Sleman',
        'price_per_night' => 1500000,
        'bedrooms' => 3,
        'max_guests' => 6,
    ]);

    expect($villa->name)->toBe('Villa Test');
    expect($villa->slug)->toBe('villa-test');
    expect($villa->is_active)->toBeTrue();
    expect((float) $villa->price_per_night)->toBe(1500000.0);
});

it('has fillable attributes', function () {
    $villa = new Villa;
    expect(in_array('name', $villa->getFillable()))->toBeTrue();
    expect(in_array('slug', $villa->getFillable()))->toBeTrue();
    expect(in_array('price_per_night', $villa->getFillable()))->toBeTrue();
    expect(in_array('weekend_price', $villa->getFillable()))->toBeTrue();
});

it('casts amenities as array', function () {
    $villa = Villa::factory()->create(['amenities' => ['WiFi', 'Pool', 'AC']]);
    expect($villa->amenities)->toBeArray();
    expect($villa->amenities)->toContain('WiFi');
});

it('casts photos as array', function () {
    $villa = Villa::factory()->create(['photos' => ['https://example.com/1.jpg', 'https://example.com/2.jpg']]);
    expect($villa->photos)->toBeArray();
    expect($villa->photos)->toHaveCount(2);
});

it('has many bookings relationship', function () {
    $villa = Villa::factory()->create();
    Booking::factory()->count(3)->create(['villa_id' => $villa->id]);
    expect($villa->bookings)->toHaveCount(3);
});

it('has many reviews relationship', function () {
    $villa = Villa::factory()->create();
    Review::factory()->count(5)->create(['villa_id' => $villa->id]);
    expect($villa->reviews)->toHaveCount(5);
});

it('has many blocked dates relationship', function () {
    $villa = Villa::factory()->create();
    BlockedDate::factory()->create(['villa_id' => $villa->id, 'date' => now()->addDays(1)->toDateString()]);
    BlockedDate::factory()->create(['villa_id' => $villa->id, 'date' => now()->addDays(2)->toDateString()]);
    BlockedDate::factory()->create(['villa_id' => $villa->id, 'date' => now()->addDays(3)->toDateString()]);
    expect($villa->blockedDates)->toHaveCount(3);
});

it('has many ical links relationship', function () {
    $villa = Villa::factory()->create();
    VillaIcalLink::factory()->count(2)->create(['villa_id' => $villa->id]);
    expect($villa->icalLinks)->toHaveCount(2);
});

it('slug is generated by factory', function () {
    $villa = Villa::factory()->create(['name' => 'Villa Mewah Puncak', 'slug' => 'villa-mewah-puncak']);
    expect($villa->slug)->toBe('villa-mewah-puncak');
});

// =====================================================
// Booking Model Tests
// =====================================================

it('can create a booking', function () {
    $villa = Villa::factory()->create();
    $booking = Booking::factory()->create([
        'villa_id' => $villa->id,
        'booking_code' => 'VB-2025-0001',
        'guest_name' => 'Test Guest',
        'guest_email' => 'guest@example.com',
        'check_in' => '2026-07-01',
        'check_out' => '2026-07-04',
        'total_nights' => 3,
        'total_amount' => 3000000,
    ]);

    expect($booking->booking_code)->toBe('VB-2025-0001');
    expect($booking->status)->toBe('pending');
    expect($booking->payment_status)->toBe('unpaid');
    expect((float) $booking->total_amount)->toBe(3000000.0);
});

it('has casted date attributes', function () {
    $booking = Booking::factory()->create([
        'check_in' => '2026-07-01',
        'check_out' => '2026-07-04',
        'cancelled_at' => null,
    ]);
    expect($booking->check_in->format('Y-m-d'))->toBe('2026-07-01');
    expect($booking->cancelled_at)->toBeNull();
});

it('booking belongs to villa', function () {
    $villa = Villa::factory()->create(['name' => 'Villa Test']);
    $booking = Booking::factory()->create(['villa_id' => $villa->id]);
    expect($booking->villa)->toBeInstanceOf(Villa::class);
    expect($booking->villa->name)->toBe('Villa Test');
});

it('has one payment relationship', function () {
    $booking = Booking::factory()->create();
    Payment::factory()->create(['booking_id' => $booking->id, 'amount' => 3000000]);
    expect($booking->payment)->toBeInstanceOf(Payment::class);
    expect((float) $booking->payment->amount)->toBe(3000000.0);
});

it('has one review relationship', function () {
    $booking = Booking::factory()->create();
    Review::factory()->create(['booking_id' => $booking->id, 'villa_id' => $booking->villa_id, 'rating' => 5]);
    expect($booking->review)->toBeInstanceOf(Review::class);
    expect($booking->review->rating)->toBe(5);
});

it('has one review token relationship', function () {
    $booking = Booking::factory()->create();
    ReviewToken::factory()->create(['booking_id' => $booking->id, 'token' => 'test-token-abc']);
    expect($booking->reviewToken)->toBeInstanceOf(ReviewToken::class);
    expect($booking->reviewToken->token)->toBe('test-token-abc');
});

it('can save booking with UTM tracking data', function () {
    $booking = Booking::factory()->create([
        'utm_source' => 'google',
        'utm_medium' => 'cpc',
        'utm_campaign' => 'liburan-2025',
    ]);
    expect($booking->utm_source)->toBe('google');
    expect($booking->utm_medium)->toBe('cpc');
    expect($booking->utm_campaign)->toBe('liburan-2025');
});

// =====================================================
// Payment Model Tests
// =====================================================

it('can create a payment record', function () {
    $booking = Booking::factory()->create();
    $payment = Payment::factory()->create([
        'booking_id' => $booking->id,
        'midtrans_order_id' => 'VB-2025-0001-123456',
        'amount' => 3500000,
        'status' => 'pending',
        'snap_token' => 'snap-token-abc',
    ]);
    expect($payment->booking_id)->toBe($booking->id);
    expect($payment->status)->toBe('pending');
    expect((float) $payment->amount)->toBe(3500000.0);
});

it('casts raw_response as array', function () {
    $payment = Payment::factory()->create([
        'booking_id' => Booking::factory()->create()->id,
        'raw_response' => ['transaction_id' => 'TX-001', 'status' => 'settlement'],
    ]);
    expect($payment->raw_response)->toBeArray();
    expect($payment->raw_response['transaction_id'])->toBe('TX-001');
});

it('payment model belongs to booking', function () {
    $booking = Booking::factory()->create(['booking_code' => 'VB-2025-0002']);
    $payment = Payment::factory()->create(['booking_id' => $booking->id]);
    expect($payment->booking)->toBeInstanceOf(Booking::class);
    expect($payment->booking->booking_code)->toBe('VB-2025-0002');
});

it('has expired_at and paid_at set', function () {
    $payment = Payment::factory()->create([
        'booking_id' => Booking::factory()->create()->id,
        'expired_at' => now()->addHour(),
        'paid_at' => now(),
    ]);
    expect($payment->expired_at)->not->toBeNull();
    expect($payment->paid_at)->not->toBeNull();
});

// =====================================================
// Review Model Tests
// =====================================================

it('can create a review', function () {
    $villa = Villa::factory()->create();
    $booking = Booking::factory()->create(['villa_id' => $villa->id]);
    $review = Review::factory()->create([
        'booking_id' => $booking->id,
        'villa_id' => $villa->id,
        'guest_name' => 'Guest Reviewer',
        'rating' => 4,
        'comment' => 'Villa yang sangat bagus!',
        'is_approved' => false,
    ]);
    expect($review->rating)->toBe(4);
    expect($review->is_approved)->toBeFalse();
});

it('review model belongs to booking', function () {
    $booking = Booking::factory()->create();
    $review = Review::factory()->create(['booking_id' => $booking->id, 'villa_id' => $booking->villa_id]);
    expect($review->booking)->toBeInstanceOf(Booking::class);
});

it('review model belongs to villa', function () {
    $villa = Villa::factory()->create(['name' => 'Villa Review Test']);
    $booking = Booking::factory()->create(['villa_id' => $villa->id]);
    $review = Review::factory()->create(['booking_id' => $booking->id, 'villa_id' => $villa->id]);
    expect($review->villa->name)->toBe('Villa Review Test');
});

it('calculates average rating for a villa', function () {
    $villa = Villa::factory()->create();
    $booking = Booking::factory()->create(['villa_id' => $villa->id]);
    Review::factory()->create(['villa_id' => $villa->id, 'booking_id' => $booking->id, 'rating' => 5, 'is_approved' => true]);
    $booking2 = Booking::factory()->create(['villa_id' => $villa->id]);
    Review::factory()->create(['villa_id' => $villa->id, 'booking_id' => $booking2->id, 'rating' => 3, 'is_approved' => true]);
    $avgRating = Review::where('villa_id', $villa->id)->where('is_approved', true)->avg('rating');
    expect(round((float) $avgRating, 1))->toBe(4.0);
});

it('excludes unapproved reviews from average', function () {
    $villa = Villa::factory()->create();
    $booking = Booking::factory()->create(['villa_id' => $villa->id]);
    Review::factory()->create(['villa_id' => $villa->id, 'booking_id' => $booking->id, 'rating' => 5, 'is_approved' => false]);
    $booking2 = Booking::factory()->create(['villa_id' => $villa->id]);
    Review::factory()->create(['villa_id' => $villa->id, 'booking_id' => $booking2->id, 'rating' => 3, 'is_approved' => true]);
    $avgRating = Review::where('villa_id', $villa->id)->where('is_approved', true)->avg('rating');
    expect((float) $avgRating)->toBe(3.0);
});

// =====================================================
// ReviewToken Model Tests
// =====================================================

it('can create a review token', function () {
    $booking = Booking::factory()->create();
    $token = ReviewToken::factory()->create([
        'booking_id' => $booking->id,
        'token' => 'unique-token-xyz',
        'used' => false,
        'expires_at' => now()->addDays(30),
    ]);
    expect($token->used)->toBeFalse();
    expect($token->expires_at)->not->toBeNull();
});

it('review token belongs to booking', function () {
    $booking = Booking::factory()->create(['booking_code' => 'VB-5000']);
    $token = ReviewToken::factory()->create(['booking_id' => $booking->id]);
    expect($token->booking->booking_code)->toBe('VB-5000');
});

it('can mark token as used', function () {
    $token = ReviewToken::factory()->create(['booking_id' => Booking::factory()->create()->id, 'used' => false]);
    $token->used = true;
    $token->save();
    expect($token->fresh()->used)->toBeTrue();
});

// =====================================================
// BlockedDate Model Tests
// =====================================================

it('can create a blocked date', function () {
    $villa = Villa::factory()->create();
    $blocked = BlockedDate::factory()->create([
        'villa_id' => $villa->id,
        'date' => '2026-08-15',
        'reason' => 'Pemeliharaan rutin',
    ]);
    expect($blocked->villa_id)->toBe($villa->id);
    expect($blocked->reason)->toBe('Pemeliharaan rutin');
});

// =====================================================
// VillaIcalLink Model Tests
// =====================================================

it('can create an ical link', function () {
    $villa = Villa::factory()->create();
    $link = VillaIcalLink::factory()->create([
        'villa_id' => $villa->id,
        'channel_name' => 'Airbnb',
        'ical_url' => 'https://www.airbnb.com/calendar/ical/abc123.ics',
        'sync_status' => 'active',
    ]);
    expect($link->channel_name)->toBe('Airbnb');
    expect($link->sync_status)->toBe('active');
});

// =====================================================
// Destination Model Tests
// =====================================================

it('can create a destination', function () {
    $dest = Destination::factory()->create(['name' => 'Puncak, Bogor', 'city' => 'Puncak', 'query' => 'Bogor']);
    expect($dest->name)->toBe('Puncak, Bogor');
    expect($dest->city)->toBe('Puncak');
});

// =====================================================
// Factory Tests
// =====================================================

it('villa factory creates valid active villa', function () {
    $villa = Villa::factory()->create();
    expect($villa->is_active)->toBeTrue();
    expect($villa->name)->not->toBeEmpty();
    expect($villa->price_per_night)->toBeGreaterThan(0);
});

it('booking factory creates valid booking', function () {
    $booking = Booking::factory()->create();
    expect($booking->booking_code)->not->toBeEmpty();
    expect($booking->guest_name)->not->toBeEmpty();
    expect($booking->total_nights)->toBeGreaterThan(0);
});
